name: kazsaq_datahub
description: "DataHub ВУЗ-ов РК - общий каталог университетов"
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  animations: ^2.0.11
  page_transition: ^2.1.0
  flutter_staggered_animations: ^1.1.1
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.9.0
  webview_flutter_web: ^0.2.2+4
  share_plus: ^10.1.2
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  expandable: ^5.0.1
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.2
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/LOGOphone.png"
  min_sdk_android: 23
  adaptive_icon_background: "#1A1A1A"
  adaptive_icon_foreground: "assets/LOGOphone.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/uniphoto/
    - assets/LOGOphone.png